# ----
# Site

title: Sun 21 Apr 2024
url: 
baseurl:The Word 1-2-1 
google_analytics_key:
show_full_navigation: true 
The Lord is my shepherd, I shall not want; the earth is full of the steadfast love of the Lord. by the word of the Lord the heavens were made, and all their host by the breath of his mouth. Psalm 23.1 and 33.5-6
# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /churchIcon.png
description:
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: 
  links:
    - https://github.com/CloudCannon/edition-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
